CREATE TABLE IF NOT EXISTS spring_users (
    id_user bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name varchar(2255),
    second_name varchar(255),
    third_name varchar(255),
    login varchar(255) NOT NULL,
    email varchar(255) NOT NULL,
    password varchar NOT NULL,
    disabled boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS spring_groups (
    id_group integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    r_group integer,
    title varchar,
    comment varchar,
    align integer NOT NULL DEFAULT 0,
    id_user bigint NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS spring_express_type (
    id_type integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS spring_express (
    id_express integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title varchar,
    about varchar,
    uri varchar,
    id_group integer NOT NULL DEFAULT 1,
    align integer NOT NULL DEFAULT 0,
    body text,
    id_type integer NOT NULL DEFAULT 1,
    id_user bigint NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS spring_files (
    id_file integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar NOT NULL,
    file varchar NOT NULL,
    content_type varchar,
    size bigint NOT NULL,
    ext varchar(50)
);

CREATE TABLE IF NOT EXISTS spring_express_files (
    id_express integer NOT NULL,
    id_file integer NOT NULL
);

CREATE TABLE IF NOT EXISTS spring_thumbs (
    id_thumbs bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file varchar NOT NULL,
    thumb varchar NOT NULL
);

ALTER TABLE spring_groups
    ADD COLUMN IF NOT EXISTS r_group integer,
    ADD COLUMN IF NOT EXISTS title varchar,
    ADD COLUMN IF NOT EXISTS comment varchar,
    ADD COLUMN IF NOT EXISTS align integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS id_user bigint NOT NULL DEFAULT 1;

ALTER TABLE spring_express
    ADD COLUMN IF NOT EXISTS date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS title varchar,
    ADD COLUMN IF NOT EXISTS about varchar,
    ADD COLUMN IF NOT EXISTS uri varchar,
    ADD COLUMN IF NOT EXISTS id_group integer NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS align integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS body text,
    ADD COLUMN IF NOT EXISTS id_type integer NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS id_user bigint NOT NULL DEFAULT 1;

ALTER TABLE spring_express_type
    ADD COLUMN IF NOT EXISTS title varchar;

ALTER TABLE spring_files
    ADD COLUMN IF NOT EXISTS name varchar,
    ADD COLUMN IF NOT EXISTS file varchar,
    ADD COLUMN IF NOT EXISTS content_type varchar,
    ADD COLUMN IF NOT EXISTS size bigint,
    ADD COLUMN IF NOT EXISTS ext varchar(50);

ALTER TABLE spring_express_files
    ADD COLUMN IF NOT EXISTS id_express integer,
    ADD COLUMN IF NOT EXISTS id_file integer;

ALTER TABLE spring_thumbs
    ADD COLUMN IF NOT EXISTS file varchar,
    ADD COLUMN IF NOT EXISTS thumb varchar;

ALTER TABLE spring_users
    ADD COLUMN IF NOT EXISTS first_name varchar(2255),
    ADD COLUMN IF NOT EXISTS second_name varchar(255),
    ADD COLUMN IF NOT EXISTS third_name varchar(255),
    ADD COLUMN IF NOT EXISTS login varchar(255),
    ADD COLUMN IF NOT EXISTS email varchar(255),
    ADD COLUMN IF NOT EXISTS password varchar,
    ADD COLUMN IF NOT EXISTS disabled boolean NOT NULL DEFAULT false;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'spring_users_email_unique'
    ) THEN
        ALTER TABLE spring_users ADD CONSTRAINT spring_users_email_unique UNIQUE (email);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'spring_users_login_unique'
    ) THEN
        ALTER TABLE spring_users ADD CONSTRAINT spring_users_login_unique UNIQUE (login);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'spring_express_type_title_unique'
    ) THEN
        ALTER TABLE spring_express_type ADD CONSTRAINT spring_express_type_title_unique UNIQUE (title);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'spring_files_unique'
    ) THEN
        ALTER TABLE spring_files ADD CONSTRAINT spring_files_unique UNIQUE (file);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'spring_thumbs_unique'
    ) THEN
        ALTER TABLE spring_thumbs ADD CONSTRAINT spring_thumbs_unique UNIQUE (thumb);
    END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS spring_express_files_id_express_idx
    ON spring_express_files (id_express, id_file);

CREATE INDEX IF NOT EXISTS spring_express_id_user_idx
    ON spring_express (id_user);

CREATE INDEX IF NOT EXISTS spring_groups_id_user_idx
    ON spring_groups (id_user);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'spring_groups_spring_groups_fk'
    ) THEN
        ALTER TABLE spring_groups
            ADD CONSTRAINT spring_groups_spring_groups_fk
                FOREIGN KEY (r_group) REFERENCES spring_groups(id_group) ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'spring_groups_spring_users_fk'
    ) THEN
        ALTER TABLE spring_groups
            ADD CONSTRAINT spring_groups_spring_users_fk
                FOREIGN KEY (id_user) REFERENCES spring_users(id_user) ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'spring_express_spring_groups_fk'
    ) THEN
        ALTER TABLE spring_express
            ADD CONSTRAINT spring_express_spring_groups_fk
                FOREIGN KEY (id_group) REFERENCES spring_groups(id_group) ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'spring_express_spring_express_type_fk'
    ) THEN
        ALTER TABLE spring_express
            ADD CONSTRAINT spring_express_spring_express_type_fk
                FOREIGN KEY (id_type) REFERENCES spring_express_type(id_type);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'spring_express_spring_users_fk'
    ) THEN
        ALTER TABLE spring_express
            ADD CONSTRAINT spring_express_spring_users_fk
                FOREIGN KEY (id_user) REFERENCES spring_users(id_user) ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'spring_express_files_spring_express_fk'
    ) THEN
        ALTER TABLE spring_express_files
            ADD CONSTRAINT spring_express_files_spring_express_fk
                FOREIGN KEY (id_express) REFERENCES spring_express(id_express) ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'spring_express_files_spring_files_fk'
    ) THEN
        ALTER TABLE spring_express_files
            ADD CONSTRAINT spring_express_files_spring_files_fk
                FOREIGN KEY (id_file) REFERENCES spring_files(id_file) ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'spring_thumbs_spring_files_fk'
    ) THEN
        ALTER TABLE spring_thumbs
            ADD CONSTRAINT spring_thumbs_spring_files_fk
                FOREIGN KEY (file) REFERENCES spring_files(file) ON DELETE CASCADE;
    END IF;
END $$;

COMMENT ON TABLE spring_express_files IS 'Files for express panels';
COMMENT ON TABLE spring_files IS 'Files';
COMMENT ON COLUMN spring_files.name IS 'File name';
COMMENT ON COLUMN spring_files.file IS 'File name in the storage (with path)';
COMMENT ON TABLE spring_thumbs IS 'Thumbs cache';
COMMENT ON COLUMN spring_thumbs.file IS 'Filename';

INSERT INTO spring_users (id_user, login, email, password, disabled)
VALUES (1, 'system@localhost', 'system@localhost', '$2a$10$uHlFtvUMpjRr9a9u8gOUeOCcxOk/jsMH5dnDJRfI2UhfVeuDic8Pe', true)
ON CONFLICT (id_user) DO NOTHING;

INSERT INTO spring_groups (id_group, r_group, title, comment, align, id_user)
VALUES (1, NULL, 'Экспресс панель', NULL, 0, 1)
ON CONFLICT (id_group) DO NOTHING;

INSERT INTO spring_express_type (id_type, title)
VALUES
    (1, 'Ссылка'),
    (2, 'Заметка'),
    (3, 'Файл')
ON CONFLICT (id_type) DO NOTHING;

SELECT setval(
    pg_get_serial_sequence('spring_users', 'id_user'),
    COALESCE((SELECT MAX(id_user) FROM spring_users), 1),
    (SELECT MAX(id_user) IS NOT NULL FROM spring_users)
);

SELECT setval(
    pg_get_serial_sequence('spring_groups', 'id_group'),
    COALESCE((SELECT MAX(id_group) FROM spring_groups), 1),
    (SELECT MAX(id_group) IS NOT NULL FROM spring_groups)
);

SELECT setval(
    pg_get_serial_sequence('spring_express_type', 'id_type'),
    COALESCE((SELECT MAX(id_type) FROM spring_express_type), 1),
    (SELECT MAX(id_type) IS NOT NULL FROM spring_express_type)
);

SELECT setval(
    pg_get_serial_sequence('spring_express', 'id_express'),
    COALESCE((SELECT MAX(id_express) FROM spring_express), 1),
    (SELECT MAX(id_express) IS NOT NULL FROM spring_express)
);

SELECT setval(
    pg_get_serial_sequence('spring_files', 'id_file'),
    COALESCE((SELECT MAX(id_file) FROM spring_files), 1),
    (SELECT MAX(id_file) IS NOT NULL FROM spring_files)
);

SELECT setval(
    pg_get_serial_sequence('spring_thumbs', 'id_thumbs'),
    COALESCE((SELECT MAX(id_thumbs) FROM spring_thumbs), 1),
    (SELECT MAX(id_thumbs) IS NOT NULL FROM spring_thumbs)
);
