CREATE TABLE IF NOT EXISTS spring_roles (
    id_role bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    title varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS spring_users_roles (
    id_user bigint NOT NULL,
    id_role bigint NOT NULL,
    CONSTRAINT spring_users_roles_pk PRIMARY KEY (id_user, id_role)
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'spring_roles_name_unique'
    ) THEN
        ALTER TABLE spring_roles ADD CONSTRAINT spring_roles_name_unique UNIQUE (name);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'spring_users_roles_users_fk'
    ) THEN
        ALTER TABLE spring_users_roles
            ADD CONSTRAINT spring_users_roles_users_fk
                FOREIGN KEY (id_user) REFERENCES spring_users(id_user) ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'spring_users_roles_roles_fk'
    ) THEN
        ALTER TABLE spring_users_roles
            ADD CONSTRAINT spring_users_roles_roles_fk
                FOREIGN KEY (id_role) REFERENCES spring_roles(id_role) ON DELETE CASCADE;
    END IF;
END $$;

INSERT INTO spring_roles (name, title)
SELECT 'ROLE_USER', 'Пользователь'
WHERE NOT EXISTS (SELECT 1 FROM spring_roles WHERE name = 'ROLE_USER');

INSERT INTO spring_roles (name, title)
SELECT 'ROLE_ADMIN', 'Администратор'
WHERE NOT EXISTS (SELECT 1 FROM spring_roles WHERE name = 'ROLE_ADMIN');

INSERT INTO spring_users_roles (id_user, id_role)
SELECT u.id_user, r.id_role
FROM spring_users u
JOIN spring_roles r ON r.name = 'ROLE_USER'
WHERE NOT EXISTS (
    SELECT 1 FROM spring_users_roles ur WHERE ur.id_user = u.id_user
);
